version: "3"
services:
  mysql:
    image: mysql:5.7
    restart: on-failure
    environment:
      - "MYSQL_ALLOW_EMPTY_PASSWORD=yes"
    volumes:
      - "./docker/mysql/data:/var/lib/mysql"
      - "./docker/mysql/config/custom.cnf:/etc/mysql/conf.d/custom.cnf"
      - "./docker/mysql/config/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    links:
      - mysql
    ports:
      - 8090:80
    environment:
      - PMA_ARBITRARY=1

  composer:
    build:
      context: "."
      dockerfile: "./docker/composer/Dockerfile"
    restart: on-failure
    command: start
    volumes:
      - "./docker/composer/logs:/logs"
      - ".:/app"
    ports:
      - "8080:8080"
    environment:
      - "ADMIN_USERNAME=admin"
      - "ADMIN_PASSWORD=admin"
      - "AUTHENTICABLE_SECRET=!s3cr3t[%s][%s]"
      - "CONTROLLER_BUNDLES_SERVER_ADDRESS=http://localhost:3000"
      - "ELASTICSEARCH_HOST=elasticsearch"
      - "PDO_DNS=mysql:dbname=spa;host=mysql;charset=utf8"
      - "PDO_USERNAME=root"
      - "PDO_PASSWORD="

  node:
    image: node:8.11
    command: npm run start
    working_dir: /usr/app
    volumes:
      - ".:/usr/app"
    ports:
      - "3000:3000"

  elasticsearch:
    build:
      context: "."
      dockerfile: "./docker/elasticsearch/Dockerfile"
    ports:
      - "9200:9200"
      - "9300:9300"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - "./docker/elasticsearch/data:/usr/share/elasticsearch/data"
      - "./docker/elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml"
      - "./docker/elasticsearch/config/logging.yml:/usr/share/elasticsearch/config/logging.yml"
      # - "./elasticsearch/config/userdict_ja.txt:/usr/share/elasticsearch/config/userdict_ja.txt"
      - "./docker/elasticsearch/logs:/var/log/elasticsearch"
    environment:
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - "bootstrap.memory_lock=true"
      - "xpack.security.enabled=false"
      - "xpack.graph.enabled=false"
      - "xpack.ml.enabled=false"
      - "xpack.monitoring.enabled=true"
      - "xpack.watcher.enabled=false"

  kibana:
    image: docker.elastic.co/kibana/kibana:6.1.4
    ports:
      - "5601:5601"
    environment:
      - "xpack.security.enabled=false"

volumes:
  mysql: {}
  elasticsearch: {}
